// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgzdOVMZm_Wm73V4bysn2_JSFItws_IVM',
    appId: '1:803778635482:web:60291b662118e0edb527e3',
    messagingSenderId: '803778635482',
    projectId: 'codeIT',
    authDomain: 'codeIT.firebaseapp.com',
    storageBucket: 'codeIT.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLlTQP71f_AztY_GbmCehRGb-_5ORsvRo',
    appId: '1:803778635482:android:c9789a28e5db6dedb527e3',
    messagingSenderId: '803778635482',
    projectId: 'codeIT',
    storageBucket: 'codeIT.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdzGdqPOvDiTTIVf801oN1vSwSi0kzXgg',
    appId: '1:803778635482:ios:eed655e77d11746db527e3',
    messagingSenderId: '803778635482',
    projectId: 'codeIT',
    storageBucket: 'codeIT.appspot.com',
    iosBundleId: 'com.example.realpalooza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdzGdqPOvDiTTIVf801oN1vSwSi0kzXgg',
    appId: '1:803778635482:ios:f4b75a4a590455f7b527e3',
    messagingSenderId: '803778635482',
    projectId: 'codeIT',
    storageBucket: 'codeIT.appspot.com',
    iosBundleId: 'com.example.realpalooza.RunnerTests',
  );
}
